server:
    port: 8003
#注册中心配置
eureka:
    client:
        serviceUrl:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-server-peer1:8000/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-server-peer1:9000/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
# 数据库相关配置
spring:
    datasource:
        druid:
            url: jdbc:mysql://116.62.143.57:3306/duobei?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            password: Hjn184736351
            username: root
    #redis
    # Redis服务器地址
    redis:
        host: 116.62.143.57
        # Redis服务器连接端口
        port: 6379
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器连接密码（默认为空）
        password: mqfq123456
        # 连接超时时间（毫秒）
        timeout: 10000s
        # Lettuce
        # 连接池最大连接数（使用负值表示没有限制）
        lettuce.pool.max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        lettuce.pool.max-wait: 10000s
        # 连接池中的最大空闲连接
        lettuce.pool.max-idle: 8
        # 连接池中的最小空闲连接
        lettuce.pool.min-idle: 0
        # 关闭超时时间
        lettuce.shutdown-timeout: 100s
