spring:
    aop:
        proxy-target-class: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            initial-size: 1
            max-active: 20
            min-idle: 1
            max-wait: 60000
            validation-query: select 'x'
            validationQueryTimeout: 5
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            aop-patterns: com.pgy.data.ms.biz.demo.svc.*.*.*
            filter:
                slf4j:
                    enabled: true
                stat:
                    db-type: mysql
                    log-slow-sql: true
                    merge-sql: true
                    slow-sql-millis: 1000
                wall:
                    config:
                        delete-allow: true
                        drop-table-allow: false
                    enabled: true
            filters: stat,wall
            stat-view-servlet:
                enabled: true
                login-password: admin123
                login-username: admin
                reset-enable: true
                url-pattern: /druid/*
            use-global-data-source-stat: true
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
                principal-session-name: user
                profile-enable: true
                session-stat-enable: true
                session-stat-max-count: 10
                url-pattern: /*
