#application-eureka-server-peer2.yml
server: 
  port: ${EUREKA_PORT:9000}

spring:
  application:
    name: eureka-server-p2  #注册中心
  #Eureka注册中心访问认证
  security:
    user:
      name: ginko
      password: 123456

eureka: 
  instance:
    hostname: eureka-server-peer2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-server-peer1:8000/eureka/  # 向peer1进行注册


info: #/info请求的显示信息
  app:
    name: ${spring.application.name}
    version: 1.0.0
  build:
    artifactId: @project.artifactId@
    version: @project.version@